export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'
export const SET_GENRES = 'SET_GENRES'
export const SET_ALBUMS = 'SET_ALBUMS'
export const SET_ARTISTS = 'SET_ARTISTS'

// Player
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const PLAYER_TOGGLE = 'PLAYER_TOGGLE'
export const PLAY_SONG = 'PLAY_SONG'
export const ADD_SONG = 'ADD_SONG'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE'
export const CLEAR_QUEUE = 'CLEAR_QUEUE'
export const PLAYER_NEXT = 'PLAYER_NEXT'
export const PLAYER_PREVIOUS = 'PLAYER_PREVIOUS'
export const PLAY_ALBUM = 'PLAY_ALBUM'
export const ADD_ALBUM = 'ADD_ALBUM'

export const _REFRESH_TIME = '_REFRESH_TIME'

export const SET_ALBUM_DATA = 'SET_ALBUM_DATA'
export const SET_LIB_PATH = 'SET_LIB_PATH'
export const SHOW_GENRES = 'SHOW_GENRES'
